Umbraco-B2B/Umbraco-B2B/Controllers/GlobalSurfaceController.cs
namespace Umbraco_Application.Controllers
{
    using System.Web.Mvc;

    using Umbraco.Web;
    using Umbraco.Web.Mvc;

    using Umbraco_Application.ContentModels;

    using Umbraco_Application.SiteConstants;

    public class GlobalSurfaceController : SurfaceController
    {
        // GET: GlobalSurface
        public ActionResult GetBrandSpecificStyleBundle()
        {
            var homePage = this.CurrentPage.AncestorOrSelf(1).OfType<HomePage>();
            var brandName = homePage.BrandName;
            var assetFolder = brandName.ToLower().Replace(" ", string.Empty);
            return this.PartialView(SiteConstants.PartialViewPath + "BrandSpecificStyles.cshtml", assetFolder);
        }

        public ActionResult GetHeaderNavigation()
        {
            var homePage = this.CurrentPage.AncestorOrSelf(1).OfType<HomePage>();
            var headerNav = homePage.HeaderNavigation;
           return this.PartialView(SiteConstants.PartialViewPath + "HeaderNavigation.cshtml", headerNav);
        }

        public ActionResult GetSiteName()
        {
            var homePage = this.CurrentPage.AncestorOrSelf(1).OfType<HomePage>();
            var siteName = homePage.SiteName;
            return this.PartialView(SiteConstants.PartialViewPath + "SiteName.cshtml", siteName);
        }
    }
}

Umbraco-B2B/Umbraco-B2B/Controllers/ProfileSurfaceController.cs
namespace Umbraco_Application.Controllers
{
    using System;
    using System.Text;
    using System.Web;
    using System.Web.Mvc;
    using System.Web.Security;

    using Umbraco.Core.Logging;
    using Umbraco.Web;
    using Umbraco.Web.Mvc;

    using Umbraco_Application.ContentModels;
    using Umbraco_Application.Models.ViewModels;
    using Umbraco_Application.SiteConstants;

    public class ProfileSurfaceController : SurfaceController
    {
        public ActionResult RenderLogin()
        {
            return this.PartialView(SiteConstants.PartialViewPath + "LoginPartial.cshtml");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(LoginViewModel viewModel)
        {
            try
            {
                if (this.ModelState.IsValid)
                {
                    var currentMember = this.Services.MemberService.GetByUsername(viewModel.Email);
                    var homePage = this.CurrentPage.AncestorOrSelf(1).OfType<HomePage>();
                    var brandName = homePage.BrandName;
                    var allowedRoles = brandName;
                    if (currentMember == null)
                    {
                        this.ModelState.AddModelError(string.Empty, "The user does not exist.");
                        return this.CurrentUmbracoPage();
                    }

                    if (currentMember.IsLockedOut)
                    {
                        this.ModelState.AddModelError(
                            string.Empty,
                            "Account locked out. Please contact our administrator.");
                        return this.CurrentUmbracoPage();
                    }

                    if (!Roles.IsUserInRole(viewModel.Email, allowedRoles))
                    {
                        this.ModelState.AddModelError(string.Empty, "The user does not exist.");
                        return this.CurrentUmbracoPage();
                    }

                    var loggedIn = this.Members.Login(viewModel.Email, viewModel.Password);
                    if (loggedIn)
                    {
                        FormsAuthentication.SetAuthCookie(viewModel.Email, false);
                        var userCookie =
                            new HttpCookie("logincookie-" + brandName)
                            {
                                Value = Convert.ToBase64String(MachineKey.Protect(Encoding.UTF8.GetBytes(currentMember.Username), "ProtectCookie")),
                                Expires = DateTime.Now.AddMinutes(180),
                                Domain = this.Request.Url.Host
                            };
                        this.Response.Cookies.Add(userCookie);
                        var redirectUrl = homePage.FirstChild<QueryPage>().Url;
                        return this.Redirect(redirectUrl);
                    }

                    this.ModelState.AddModelError(string.Empty, "Wrong username or password entered.");
                    return this.CurrentUmbracoPage();
                }

                return this.CurrentUmbracoPage();
            }
            catch (Exception exception)
            {
                LogHelper.Error<ProfileSurfaceController>("error while logging in", exception);
                return this.CurrentUmbracoPage();
            }
        }

        public ActionResult HandleLogout()
        {
            var homePage = this.CurrentPage.AncestorOrSelf(1).OfType<HomePage>();
            var brandName = homePage.BrandName;
            var cookieName = "logincookie-" + brandName;
            this.TempData.Clear();
            this.Session.Clear();
            FormsAuthentication.SignOut();
            if (this.Request.Cookies[cookieName] != null)
            {
                this.Response.Cookies[cookieName].Expires = DateTime.Now.AddDays(-1);
            }

            return this.Redirect("/");
        }
    }
}

Umbraco-B2B/Umbraco-B2B/Controllers/QuerySurfaceController.cs
namespace Umbraco_Application.Controllers
{
    using System.Collections.Generic;
    using System.Linq;
    using System.Web.Mvc;

    using Umbraco.Core.Models;
    using Umbraco.Web;
    using Umbraco.Web.Mvc;

    using Umbraco_Application.ContentModels;
    using Umbraco_Application.Models.ViewModels;
    using Umbraco_Application.SiteConstants;

    public class QuerySurfaceController : SurfaceController
    {
        public ActionResult RenderQuery()
        {
            var homePage = this.CurrentPage.AncestorOrSelf(1).OfType<HomePage>();
            var categoryNodes = homePage.Descendants("Category");
            var categories = categoryNodes.Select(category => new SelectListItem() { Text = category.Name, Value = category.GetKey().ToString() }).ToList();
             var currentMember = this.Members.GetCurrentMember();
            var currentMemberProducts = currentMember.GetPropertyValue<IEnumerable<IPublishedContent>>("availableProducts");
            var products = currentMemberProducts.Select(product => new SelectListItem() { Text = product.Name, Value = product.GetKey().ToString() }).ToList();
            var viewModel = new QueryViewModel() {MemberId = currentMember.GetKey(), MemberName = currentMember.Name, MemberEmail = this.Members.CurrentUserName, Categories = new SelectList(categories, "Value","Text"), Products = new SelectList(products, "Value", "Text"), IsReseller = homePage.IsResellerSite};
            return this.PartialView(SiteConstants.PartialViewPath + "Query.cshtml", viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SubmitQuery(QueryViewModel viewModel)
        {
            this.ViewData["Message"] = "Thank you";
            return this.CurrentUmbracoPage();
           }
    }
}

Umbraco-B2B/Umbraco-B2B/Views/ContentPage.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<Umbraco_Application.ContentModels.ContentPage>
@{
	Layout = "_Layout.cshtml";
}
<h1>@Model.Name</h1>
@Model.BodyText

Umbraco-B2B/Umbraco-B2B/Views/Home.cshtml
@using System.Web.Optimization
@inherits Umbraco.Web.Mvc.UmbracoViewPage<Umbraco_Application.ContentModels.HomePage>
@{
    Layout = "_Layout.cshtml";
}
<h1>@Model.Name</h1>


@Html.Action("RenderLogin","ProfileSurface")


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Umbraco-B2B/Umbraco-B2B/Views/QueryPage.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<Umbraco_Application.ContentModels.QueryPage>
@{
	Layout = "_Layout.cshtml";
}
<h1>@Model.Name</h1>

@Html.Action("RenderQuery","QuerySurface")

Umbraco-B2B/Umbraco-B2B/Views/_Layout.cshtml
@using System.Web.Optimization
@inherits UmbracoViewPage
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@Model.Name</title>
    @Styles.Render("~/bundles/css")
    @Scripts.Render("~/bundles/modernizr")
    @Html.Action("GetBrandSpecificStyleBundle", "GlobalSurface")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">Home</a>
            </div>
            <div class="navbar-collapse collapse">
                @Html.Action("GetHeaderNavigation", "GlobalSurface")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        @Html.Action("GetSiteName", "GlobalSurface")
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>